apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-server.yaml
  - ./svc-server.yaml
  
configMapGenerator:
  - name: env
    literals:
      - ARCHIVE_URL=https://archive-api.lco.global/frames/
      - OBSPORTAL_AUTH_URL=https://observe.lco.global/api/api-token-auth/
