# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/component: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - name: redis
          image: redis:7.4.1
          ports:
          - containerPort: 6379
          volumeMounts:
          - name: redis-data
            mountPath: /data
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 3
            exec:
              command:
              - redis-cli
              - ping
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 3
            exec:
              command:
              - redis-cli
              - ping
